
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author jaffe
 */
public class Principal extends javax.swing.JFrame {

    private CrudSQL objCross = new CrudSQL();
    AtencionesPantalla atencion = new AtencionesPantalla();

    private boolean cubiculoLavado1 = false;
    private boolean cubiculoLavado2 = false;
    private boolean cubiculoSecado1 = false;
    private boolean cubiculoSecado2 = false;

    public AtencionesPantalla cubiculoLav1;
    public AtencionesPantalla cubiculoLav2;
    public AtencionesSec cubiculoSec1;
    public AtencionesSec cubiculoSec2;

    public AtencionesPantalla tipoEstadoLav1;
    public AtencionesPantalla tipoEstadoLav2;
    public AtencionesPantalla tipoEstadoSec1;
    public AtencionesPantalla tipoEstadoSec2;

    private int ordenEspera = 0;

    /**
     * Creates new form Principal
     */
    ArrayList<AtencionesPantalla> atencionesLav = new ArrayList<>();
    ArrayList<AtencionesSec> atencionesSec = new ArrayList<>();

    public Principal() {

        super("Brillo Bonito");

        CrudSQL objcross = new CrudSQL();

        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

        objcross.ObtenerAtencionesEsperaLav();

        //if(lbl_codigoEspera1){
        //}
        atencionesLav = objCross.ObtenerAtencionesEsperaLav();
        atencionesSec = objCross.ObtenerAtencionesEsperaSec();

        UpdateList();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_codigoEspera2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_nombreEspera2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbl_empleadoEspera2 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbl_placaEspera2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lbl_codigoEspera1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lbl_nombreEspera1 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lbl_empleadoEspera1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lbl_placaEspera1 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_vaciarSec1 = new javax.swing.JButton();
        btn_vaciarSec2 = new javax.swing.JButton();
        btn_vaciarLav1 = new javax.swing.JButton();
        btn_vaciarLav2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_carroSec1 = new javax.swing.JLabel();
        lbl_carroSec2 = new javax.swing.JLabel();
        lbl_carroLav1 = new javax.swing.JLabel();
        lbl_carroLav2 = new javax.swing.JLabel();
        btn_siguienteSec = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_codigoSec1 = new javax.swing.JTextField();
        txt_nombreSec1 = new javax.swing.JTextField();
        txt_empleadoSec1 = new javax.swing.JTextField();
        txt_placaSec1 = new javax.swing.JTextField();
        txt_codigoSec2 = new javax.swing.JTextField();
        txt_nombreSec2 = new javax.swing.JTextField();
        txt_empleadoSec2 = new javax.swing.JTextField();
        txt_placaSec2 = new javax.swing.JTextField();
        txt_codigoLav1 = new javax.swing.JTextField();
        txt_nombreLav1 = new javax.swing.JTextField();
        txt_empleadoLav1 = new javax.swing.JTextField();
        txt_placaLav1 = new javax.swing.JTextField();
        txt_codigoLav2 = new javax.swing.JTextField();
        txt_nombreLav2 = new javax.swing.JTextField();
        txt_empleadoLav2 = new javax.swing.JTextField();
        txt_placaLav2 = new javax.swing.JTextField();
        btn_siguienteLav = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        btn_ingresar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Sala de espera");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 8, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Numero de Codigo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lbl_codigoEspera2.setText("jLabel21");
        jPanel1.add(lbl_codigoEspera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel24.setText("Nombre:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lbl_nombreEspera2.setText("jLabel26");
        jPanel1.add(lbl_nombreEspera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel29.setText("Empleado:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        lbl_empleadoEspera2.setText("jLabel31");
        jPanel1.add(lbl_empleadoEspera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel34.setText("Placa:");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        lbl_placaEspera2.setText("jLabel36");
        jPanel1.add(lbl_placaEspera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel37.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel37.setText("Numero de Codigo");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        lbl_codigoEspera1.setText("jLabel21");
        jPanel1.add(lbl_codigoEspera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel39.setText("Nombre:");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        lbl_nombreEspera1.setText("jLabel26");
        jPanel1.add(lbl_nombreEspera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel41.setText("Empleado:");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        lbl_empleadoEspera1.setText("jLabel31");
        jPanel1.add(lbl_empleadoEspera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel43.setText("Placa:");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        lbl_placaEspera1.setText("jLabel36");
        jPanel1.add(lbl_placaEspera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Cubiculo 1");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Cubiculo 2");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        btn_vaciarSec1.setText("Vaciar");
        btn_vaciarSec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vaciarSec1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_vaciarSec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        btn_vaciarSec2.setText("Vaciar");
        btn_vaciarSec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vaciarSec2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_vaciarSec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        btn_vaciarLav1.setText("Vaciar");
        btn_vaciarLav1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vaciarLav1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_vaciarLav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, -1, -1));

        btn_vaciarLav2.setText("Vaciar");
        btn_vaciarLav2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vaciarLav2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_vaciarLav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Cubiculo 1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Cubiculo 2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        lbl_carroSec1.setBackground(new java.awt.Color(0, 255, 0));
        lbl_carroSec1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_carroSec1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_carroSec1.setOpaque(true);
        jPanel2.add(lbl_carroSec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 229));

        lbl_carroSec2.setBackground(new java.awt.Color(0, 255, 0));
        lbl_carroSec2.setOpaque(true);
        jPanel2.add(lbl_carroSec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 130, 229));

        lbl_carroLav1.setBackground(new java.awt.Color(0, 255, 0));
        lbl_carroLav1.setOpaque(true);
        jPanel2.add(lbl_carroLav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 130, 229));

        lbl_carroLav2.setBackground(new java.awt.Color(0, 255, 0));
        lbl_carroLav2.setOpaque(true);
        jPanel2.add(lbl_carroLav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 130, 229));

        btn_siguienteSec.setText("Siguiente");
        btn_siguienteSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteSecActionPerformed(evt);
            }
        });
        jPanel2.add(btn_siguienteSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Numero Codigo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Numero Codigo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Numero Codigo");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Numero Codigo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        jLabel15.setText("Secado");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        jLabel16.setText("Lavado");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Nombre:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Empleado:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Placa");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Nombre:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Empleado:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setText("Placa");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Nombre:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setText("Empleado:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setText("Placa");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel32.setText("Nombre:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setText("Empleado:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        jLabel35.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel35.setText("Placa");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        txt_codigoSec1.setEditable(false);
        txt_codigoSec1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(txt_codigoSec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 110, -1));

        txt_nombreSec1.setEditable(false);
        txt_nombreSec1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(txt_nombreSec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, -1));

        txt_empleadoSec1.setEditable(false);
        txt_empleadoSec1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(txt_empleadoSec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, -1));

        txt_placaSec1.setEditable(false);
        txt_placaSec1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(txt_placaSec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 110, -1));

        txt_codigoSec2.setEditable(false);
        jPanel2.add(txt_codigoSec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 110, -1));

        txt_nombreSec2.setEditable(false);
        jPanel2.add(txt_nombreSec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 110, -1));

        txt_empleadoSec2.setEditable(false);
        jPanel2.add(txt_empleadoSec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 110, -1));

        txt_placaSec2.setEditable(false);
        jPanel2.add(txt_placaSec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 110, -1));

        txt_codigoLav1.setEditable(false);
        jPanel2.add(txt_codigoLav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 110, -1));

        txt_nombreLav1.setEditable(false);
        jPanel2.add(txt_nombreLav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 110, -1));

        txt_empleadoLav1.setEditable(false);
        jPanel2.add(txt_empleadoLav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 110, -1));

        txt_placaLav1.setEditable(false);
        txt_placaLav1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_placaLav1ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_placaLav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 110, -1));

        txt_codigoLav2.setEditable(false);
        jPanel2.add(txt_codigoLav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 110, -1));

        txt_nombreLav2.setEditable(false);
        jPanel2.add(txt_nombreLav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 110, -1));

        txt_empleadoLav2.setEditable(false);
        txt_empleadoLav2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empleadoLav2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_empleadoLav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 110, -1));

        txt_placaLav2.setEditable(false);
        jPanel2.add(txt_placaLav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 110, -1));

        btn_siguienteLav.setText("Siguiente");
        btn_siguienteLav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteLavActionPerformed(evt);
            }
        });
        jPanel2.add(btn_siguienteLav, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoCarwash.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText(" Bienvenido a CarWash Brillo Bonito.");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        btn_registrar.setBackground(new java.awt.Color(102, 255, 255));
        btn_registrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrar.setText("Registrarte");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 140, 30));

        btn_ingresar.setBackground(new java.awt.Color(102, 255, 255));
        btn_ingresar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_ingresar.setForeground(new java.awt.Color(0, 0, 0));
        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 110, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("No tienes cuenta? Registrate.");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String SetLavado(int idAtencion) {

        return objCross.Update("En Lavado", idAtencion);
    }

    public String SetSecadoEspera(int idAtencion) {

        return objCross.Update("En Espera Secado", idAtencion);
    }

    public String SetSecado(int idAtencion) {

        return objCross.Update("En Secado", idAtencion);
    }

    public String SetFinalizado(int idAtencion) {
        objCross.Delete(idAtencion);
        String estado = objCross.Update("Finalizado", idAtencion);
        JOptionPane.showMessageDialog(null, "Numero Ticket: " + idAtencion + "\n" + "Estado: Finalizado\n" + "Gracias por visitarnos.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        return estado;
    }

    public void UpdateList() {

        if (atencionesLav.size() >= 1 && atencionesLav.get(0) != null) {
            lbl_codigoEspera1.setText(atencionesLav.get(0).getCodigo());
            lbl_nombreEspera1.setText(atencionesLav.get(0).getNombre());
            lbl_empleadoEspera1.setText(atencionesLav.get(0).getEmpleado());
            lbl_placaEspera1.setText(atencionesLav.get(0).getPlaca());

        } else {
            lbl_codigoEspera1.setText("");
            lbl_nombreEspera1.setText("");
            lbl_empleadoEspera1.setText("");
            lbl_placaEspera1.setText("");
        }
        if (atencionesLav.size() >= 2 && atencionesLav.get(1) != null) {
            lbl_codigoEspera2.setText(atencionesLav.get(1).getCodigo());
            lbl_nombreEspera2.setText(atencionesLav.get(1).getNombre());
            lbl_empleadoEspera2.setText(atencionesLav.get(1).getEmpleado());
            lbl_placaEspera2.setText(atencionesLav.get(1).getPlaca());

        } else {
            lbl_codigoEspera2.setText("");
            lbl_nombreEspera2.setText("");
            lbl_empleadoEspera2.setText("");
            lbl_placaEspera2.setText("");

        }
        if (atencionesSec.size() >= 1 && atencionesSec.get(0) != null) {
            atencionesSec.get(0).getCodigo();
            atencionesSec.get(0).getNombre();
            atencionesSec.get(0).getEmpleado();
            atencionesSec.get(0).getPlaca();
        }
        if (atencionesSec.size() >= 2 && atencionesSec.get(1) != null) {
            atencionesSec.get(1).getCodigo();
            atencionesSec.get(1).getNombre();
            atencionesSec.get(1).getEmpleado();
            atencionesSec.get(1).getPlaca();

        }
    }


    private void btn_vaciarSec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vaciarSec1ActionPerformed
        try {
            String codigo = txt_codigoSec1.getText();
            int codigoPrueba = Integer.parseInt(codigo);

            String tipoLavado = objCross.ObtenerTipoLavado(codigoPrueba);

            cubiculoSec1 = new AtencionesSec();

            if (tipoLavado.equals("Lavado y Secado")) {

                cubiculoSec1.setEstado(SetFinalizado(codigoPrueba));

                lbl_carroSec1.setBackground(new Color(0, 255, 0));
                lbl_carroSec1.setIcon(null);
                txt_codigoSec1.setText(String.valueOf(""));
                txt_nombreSec1.setText(String.valueOf(""));
                txt_empleadoSec1.setText(String.valueOf(""));
                txt_placaSec1.setText(String.valueOf(""));

                cubiculoSecado1 = false;

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El cubiculo se encuantra vacio.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btn_vaciarSec1ActionPerformed

    private void btn_vaciarSec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vaciarSec2ActionPerformed
        try {
            String codigo = txt_codigoSec2.getText();
            int codigoPrueba = Integer.parseInt(codigo);

            String tipoLavado = objCross.ObtenerTipoLavado(codigoPrueba);

            cubiculoSec2 = new AtencionesSec();

            if (tipoLavado.equals("Lavado y Secado")) {

                cubiculoSec2.setEstado(SetFinalizado(codigoPrueba));

                lbl_carroSec2.setBackground(new Color(0, 255, 0));
                lbl_carroSec2.setIcon(null);
                txt_codigoSec2.setText(String.valueOf(""));
                txt_nombreSec2.setText(String.valueOf(""));
                txt_empleadoSec2.setText(String.valueOf(""));
                txt_placaSec2.setText(String.valueOf(""));

                cubiculoSecado2 = false;
                

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El cubiculo se encuantra vacio.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_vaciarSec2ActionPerformed

    private void btn_vaciarLav1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vaciarLav1ActionPerformed
        try {
            String codigo = txt_codigoLav1.getText();
            int codigoPrueba = Integer.parseInt(codigo);

            String tipoLavado = objCross.ObtenerTipoLavado(codigoPrueba);

            if (tipoLavado.equals("Lavado")) {

                cubiculoLav1.setEstado(SetFinalizado(codigoPrueba));

                lbl_carroLav1.setBackground(new Color(0, 255, 0));
                lbl_carroLav1.setIcon(null);
                txt_codigoLav1.setText(String.valueOf(""));
                txt_nombreLav1.setText(String.valueOf(""));
                txt_empleadoLav1.setText(String.valueOf(""));
                txt_placaLav1.setText(String.valueOf(""));

                cubiculoLavado1 = false;

                atencionesLav.clear();
                atencionesLav = objCross.ObtenerAtencionesEsperaLav();
                UpdateList();

                atencionesSec.clear();
                atencionesSec = objCross.ObtenerAtencionesEsperaSec();
                UpdateList();

            } else if ("Lavado y Secado".equals(tipoLavado)) {
                cubiculoLav1.setEstado(SetSecadoEspera(codigoPrueba));

                lbl_carroLav1.setBackground(new Color(0, 255, 0));
                lbl_carroLav1.setIcon(null);
                txt_codigoLav1.setText(String.valueOf(""));
                txt_nombreLav1.setText(String.valueOf(""));
                txt_empleadoLav1.setText(String.valueOf(""));
                txt_placaLav1.setText(String.valueOf(""));

                cubiculoLavado1 = false;

                atencionesLav.clear();
                atencionesLav = objCross.ObtenerAtencionesEsperaLav();
                UpdateList();

                atencionesSec.clear();
                atencionesSec = objCross.ObtenerAtencionesEsperaSec();
                UpdateList();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El cubiculo se encuantra vacio.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btn_vaciarLav1ActionPerformed

    private void btn_vaciarLav2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vaciarLav2ActionPerformed
        try {
            String codigo = txt_codigoLav2.getText();
            int codigoPrueba = Integer.parseInt(codigo);

            String tipoLavado = objCross.ObtenerTipoLavado(codigoPrueba);

            if (tipoLavado.equals("Lavado")) {

                cubiculoLav2.setEstado(SetFinalizado(codigoPrueba));

                lbl_carroLav2.setBackground(new Color(0, 255, 0));
                lbl_carroLav2.setIcon(null);
                txt_codigoLav2.setText(String.valueOf(""));
                txt_nombreLav2.setText(String.valueOf(""));
                txt_empleadoLav2.setText(String.valueOf(""));
                txt_placaLav2.setText(String.valueOf(""));

                cubiculoLavado2 = false;

                atencionesLav.clear();
                atencionesLav = objCross.ObtenerAtencionesEsperaLav();
                UpdateList();

                atencionesSec.clear();
                atencionesSec = objCross.ObtenerAtencionesEsperaSec();
                UpdateList();

            } else if ("Lavado y Secado".equals(tipoLavado)) {
                cubiculoLav2.setEstado(SetSecadoEspera(codigoPrueba));

                lbl_carroLav2.setBackground(new Color(0, 255, 0));
                lbl_carroLav2.setIcon(null);
                txt_codigoLav2.setText(String.valueOf(""));
                txt_nombreLav2.setText(String.valueOf(""));
                txt_empleadoLav2.setText(String.valueOf(""));
                txt_placaLav2.setText(String.valueOf(""));

                cubiculoLavado2 = false;

                atencionesLav.clear();
                atencionesLav = objCross.ObtenerAtencionesEsperaLav();
                UpdateList();

                atencionesSec.clear();
                atencionesSec = objCross.ObtenerAtencionesEsperaSec();
                UpdateList();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El cubiculo se encuantra vacio.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btn_vaciarLav2ActionPerformed

    private void btn_siguienteSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteSecActionPerformed

        if (!atencionesSec.isEmpty()) {
            if (!cubiculoSecado1) {
                if (atencionesSec.get(0) != null) {
                    txt_codigoSec1.setText(atencionesSec.get(0).getCodigo());
                    txt_nombreSec1.setText(atencionesSec.get(0).getNombre());
                    txt_empleadoSec1.setText(atencionesSec.get(0).getEmpleado());
                    txt_placaSec1.setText(atencionesSec.get(0).getPlaca());

                    lbl_carroSec1.setBackground(new Color(255, 0, 0));

                    String nombreImagen = "Carro Gris.png";
                    String rutaImagen = "\\Imagenes\\" + nombreImagen;
                    ImageIcon icono = new ImageIcon(getClass().getResource(rutaImagen));
                    lbl_carroSec1.setIcon(icono);
                    AtencionesSec cubiculoSec1 = atencionesSec.get(0);
                    cubiculoSec1.setEstado(SetSecado(Integer.parseInt(cubiculoSec1.getCodigo())));

                    atencionesSec.remove(0);
                    cubiculoSecado1 = true;
                    atencionesLav.clear();
                    atencionesLav = objCross.ObtenerAtencionesEsperaLav();
                    UpdateList();

                    atencionesSec.clear();
                    atencionesSec = objCross.ObtenerAtencionesEsperaSec();
                    UpdateList();
                }
            } else if (!cubiculoSecado2) {
                if (atencionesSec.get(0) != null) {
                    txt_codigoSec2.setText(atencionesSec.get(0).getCodigo());
                    txt_nombreSec2.setText(atencionesSec.get(0).getNombre());
                    txt_empleadoSec2.setText(atencionesSec.get(0).getEmpleado());
                    txt_placaSec2.setText(atencionesSec.get(0).getPlaca());

                    lbl_carroSec2.setBackground(new Color(255, 0, 0));

                    String nombreImagen = "Carro Gris.png";
                    String rutaImagen = "\\Imagenes\\" + nombreImagen;
                    ImageIcon icono = new ImageIcon(getClass().getResource(rutaImagen));
                    lbl_carroSec2.setIcon(icono);
                    AtencionesSec cubiculoSec2 = atencionesSec.get(0);
                    cubiculoSec2.setEstado(SetSecado(Integer.parseInt(cubiculoSec2.getCodigo())));

                    atencionesSec.remove(0);
                    cubiculoSecado2 = true;
                    atencionesLav.clear();
                    atencionesLav = objCross.ObtenerAtencionesEsperaLav();
                    UpdateList();

                    atencionesSec.clear();
                    atencionesSec = objCross.ObtenerAtencionesEsperaSec();
                    UpdateList();
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay espacios disponibles aún.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay atenciones disponibles.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btn_siguienteSecActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        MenuIngreso menuRegistrar = new MenuIngreso();

        menuRegistrar.setVisible(true);
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        Factura menuFactura = new Factura();

        menuFactura.setVisible(true);


    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_siguienteLavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteLavActionPerformed

        if (!atencionesLav.isEmpty()) {
            if (!cubiculoLavado1) {
                if (atencionesLav.get(0) != null) {
                    txt_codigoLav1.setText(atencionesLav.get(0).getCodigo());
                    txt_nombreLav1.setText(atencionesLav.get(0).getNombre());
                    txt_empleadoLav1.setText(atencionesLav.get(0).getEmpleado());
                    txt_placaLav1.setText(atencionesLav.get(0).getPlaca());

                    lbl_carroLav1.setBackground(new Color(255, 0, 0));

                    String nombreImagen = "Carro Gris.png";
                    String rutaImagen = "\\Imagenes\\" + nombreImagen;
                    ImageIcon icono = new ImageIcon(getClass().getResource(rutaImagen));
                    lbl_carroLav1.setIcon(icono);
                    cubiculoLav1 = atencionesLav.get(0);
                    cubiculoLav1.setEstado(SetLavado(Integer.parseInt(cubiculoLav1.getCodigo())));

                    atencionesLav.remove(0);
                    cubiculoLavado1 = true;
                    atencionesLav.clear();
                    atencionesLav = objCross.ObtenerAtencionesEsperaLav();
                    UpdateList();
                }
            } else if (!cubiculoLavado2) {
                if (atencionesLav.get(0) != null) {
                    txt_codigoLav2.setText(atencionesLav.get(0).getCodigo());
                    txt_nombreLav2.setText(atencionesLav.get(0).getNombre());
                    txt_empleadoLav2.setText(atencionesLav.get(0).getEmpleado());
                    txt_placaLav2.setText(atencionesLav.get(0).getPlaca());

                    lbl_carroLav2.setBackground(new Color(255, 0, 0));

                    String nombreImagen = "Carro Gris.png";
                    String rutaImagen = "\\Imagenes\\" + nombreImagen;
                    ImageIcon icono = new ImageIcon(getClass().getResource(rutaImagen));
                    lbl_carroLav2.setIcon(icono);
                    cubiculoLav2 = atencionesLav.get(0);
                    cubiculoLav2.setEstado(SetLavado(Integer.parseInt(cubiculoLav2.getCodigo())));

                    atencionesLav.remove(0);
                    cubiculoLavado2 = true;
                    atencionesLav.clear();
                    atencionesLav = objCross.ObtenerAtencionesEsperaLav();
                    UpdateList();
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay espacios disponibles aún.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay atenciones disponibles.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_siguienteLavActionPerformed

    private void txt_placaLav1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_placaLav1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_placaLav1ActionPerformed

    private void txt_empleadoLav2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empleadoLav2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empleadoLav2ActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        atencionesLav.clear();
        atencionesLav = objCross.ObtenerAtencionesEsperaLav();
        UpdateList();

        atencionesSec.clear();
        atencionesSec = objCross.ObtenerAtencionesEsperaSec();
        UpdateList();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ConexionBD objConeccion = new ConexionBD();
        objConeccion.EstablecerConeccion();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_siguienteLav;
    private javax.swing.JButton btn_siguienteSec;
    private javax.swing.JButton btn_vaciarLav1;
    private javax.swing.JButton btn_vaciarLav2;
    private javax.swing.JButton btn_vaciarSec1;
    private javax.swing.JButton btn_vaciarSec2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_carroLav1;
    private javax.swing.JLabel lbl_carroLav2;
    private javax.swing.JLabel lbl_carroSec1;
    private javax.swing.JLabel lbl_carroSec2;
    private javax.swing.JLabel lbl_codigoEspera1;
    private javax.swing.JLabel lbl_codigoEspera2;
    private javax.swing.JLabel lbl_empleadoEspera1;
    private javax.swing.JLabel lbl_empleadoEspera2;
    private javax.swing.JLabel lbl_nombreEspera1;
    private javax.swing.JLabel lbl_nombreEspera2;
    private javax.swing.JLabel lbl_placaEspera1;
    private javax.swing.JLabel lbl_placaEspera2;
    private javax.swing.JTextField txt_codigoLav1;
    private javax.swing.JTextField txt_codigoLav2;
    private javax.swing.JTextField txt_codigoSec1;
    private javax.swing.JTextField txt_codigoSec2;
    private javax.swing.JTextField txt_empleadoLav1;
    private javax.swing.JTextField txt_empleadoLav2;
    private javax.swing.JTextField txt_empleadoSec1;
    private javax.swing.JTextField txt_empleadoSec2;
    private javax.swing.JTextField txt_nombreLav1;
    private javax.swing.JTextField txt_nombreLav2;
    private javax.swing.JTextField txt_nombreSec1;
    private javax.swing.JTextField txt_nombreSec2;
    private javax.swing.JTextField txt_placaLav1;
    private javax.swing.JTextField txt_placaLav2;
    private javax.swing.JTextField txt_placaSec1;
    private javax.swing.JTextField txt_placaSec2;
    // End of variables declaration//GEN-END:variables
}
